### ISSUE TITLE
Add libcurl 7.43 RPM for el7

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/yum#4]
@slapula could you help add the libcurl RPM as well? Thanks!

http://cbs.centos.org/kojifiles/packages/curl/7.43.0/1.el7/src/

**Comment by slapula** [comment]
This one is all taken care of! :sunglasses:

**Comment by ronaldtse** [comment]
@slapula thank you, it works 👍 

Currently the package isn't signed, so we will need to re-sign it using the repo key.

**Comment by ronaldtse** [comment]
P.S. to install them one needs to set `gpgcheck=0` in `/etc/yum.repos.d/ribose.repo` prior to installation, otherwise yum would reject them.
